version: "3"
services:
  webserver:
    container_name: menu_frontend
    image: "nginx:latest"
    volumes:
      - "./frontend:/usr/share/nginx/html"
    ports:
      - "8080:80"
    restart: unless-stopped
