- hosts: worker2
  vars_files: 
    - ./vars.yml

  handlers:
  - name: 'sleep'
    pause:
      seconds: 10

  tasks:
  - name: 'Increase Timeout'
    wait_for_connection:
      timeout: 800

  - name: 'Create Container'
    community.general.proxmox:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password_vault }}"
      api_host: "{{ api_host }}"
      vmid: "{{ vmid }}"
      hostname: "{{ hostname }}"
      password: '{{ ct_password_vault }}'
      features: '{{ features }}'
      node: '{{ node }}'
      pubkey: '{{ pubkey }}'
      cores: '{{ cores }}'
      cpus: '{{ cpu }}'
      memory: '{{ memory }}'
      swap: '{{ swap }}'
      disk: '{{ disk }}'
      storage: '{{ storage }}'
      ostemplate: '{{ ostemplate }}'
      netif: '{{ netif }}'
    register: 'created_ct'
    until: created_ct is not failed
    retries: '5'
    delay: '10'
    failed_when: '"already exists" not in created_ct.msg'
    notify:
      - 'sleep'

  - name: 'Start Container'
    community.general.proxmox:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password_vault }}"
      api_host: "{{ api_host }}"
      node: '{{ node }}'
      hostname: "{{ hostname }}"
      state: 'started'
    when: created_ct is succeeded
    
  - name: 'Wait for port 22 to become open'
    wait_for:
      port: 22
      host: "{{ ct_host }}"
      delay: 20 
  
- hosts: container
  become: yes
  vars_files: 
    - ./vars.yml  

  tasks:
  - name: 'Instalar Docker en CT'
    include_tasks: install_docker.yml
