api_user: 'root@pam'
api_password_vault: 'my_password'
api_host: '192.168.1.101'
ct_password_vault: 'my_password'
features:
 - nesting=1
pubkey: "{{ lookup('file', '/root/.ssh/ansible_rsa.pub') }}"

#-----EDITABLE-----
vmid: '100'
hostname: 'Gitlab-Server'
cores: '2'
cpu: '2'
memory: '4096'
swap: '4096'
node: 'proxmox1'
disk: '50'
storage: 'local-lvm'
ostemplate: 'local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'
netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.105/24,bridge=vmbr0"}'

#-----CONTAINER IP-----
ct_host: '192.168.1.105'
