version: "3"
services:
  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./phpfiles:/var/www/html
    depends_on:
      - "bbdd"

  bbdd:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: inventario
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PORT: 3306
    volumes:
      - ./.db_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
